"""
pdf_export.py — Convert client Markdown report to styled PDF via WeasyPrint.
WeasyPrint requires GTK runtime on Windows (libgobject-2.0-0).
Import is deferred so the server starts even without GTK installed.
"""
import markdown as md


_STYLES = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    font-size: 13px;
    line-height: 1.6;
    color: #1e293b;
    background: #fff;
    padding: 48px 52px;
}

h1 { font-size: 22px; font-weight: 700; color: #0f172a; margin-bottom: 4px; }
h2 { font-size: 15px; font-weight: 600; color: #0f172a; margin-top: 28px; margin-bottom: 10px;
     border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
h3 { font-size: 13px; font-weight: 600; color: #334155; margin-top: 16px; margin-bottom: 6px; }

p { margin-bottom: 8px; color: #475569; }

ul, ol { padding-left: 20px; margin-bottom: 10px; }
li { margin-bottom: 3px; color: #475569; }

table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
th { background: #f1f5f9; color: #0f172a; font-weight: 600; text-align: left;
     padding: 7px 10px; border: 1px solid #e2e8f0; }
td { padding: 6px 10px; border: 1px solid #e2e8f0; color: #475569; }
tr:nth-child(even) td { background: #f8fafc; }

code { font-family: 'Courier New', monospace; font-size: 11px;
       background: #f1f5f9; padding: 1px 5px; border-radius: 3px; }

a { color: #3b82f6; text-decoration: none; }

.header-bar {
    background: #0f172a;
    color: #fff;
    padding: 18px 24px;
    border-radius: 8px;
    margin-bottom: 28px;
}
.header-bar h1 { color: #fff; }
.header-bar p { color: #94a3b8; font-size: 12px; margin: 0; }

hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }

@page {
    margin: 0;
    size: A4;
}
"""


def generate_pdf(report_markdown: str, title: str = "SEO Audit Report") -> bytes:
    try:
        from weasyprint import HTML, CSS
    except OSError as exc:
        raise RuntimeError(
            "WeasyPrint could not load system libraries (GTK runtime missing on Windows). "
            "Install the GTK3 runtime from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer "
            "or use the Markdown/CSV export instead."
        ) from exc

    html_body = md.markdown(report_markdown, extensions=["tables", "fenced_code"])
    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{title}</title></head>
<body>
<div class="header-bar">
  <h1>{title}</h1>
  <p>Generated by SEO Crawler</p>
</div>
{html_body}
</body>
</html>"""
    return HTML(string=full_html).write_pdf(stylesheets=[CSS(string=_STYLES)])
